version: '3.4'
services:
  frontend:
    container_name: glygen-frontend-test
    image: glygen-frontend-test:latest
    build:
      args:
        - REACT_APP_ENV=test
        - REACT_APP_BUILD=biomarker
        - REACT_APP_API=https://api.tst.glygen.org
        - REACT_APP_DOMAIN=https://tst.glygen.org
        # - REACT_APP_DOMAIN=http://localhost:4040
        - REACT_APP_BETA_DOMAIN=https://beta.glygen.org
        - REACT_APP_DATA=https://data.tst.glygen.org
        - REACT_APP_SPARQL=https://sparql.tst.glygen.org
        - REACT_APP_BASENAME=/
        - GENERATE_SOURCEMAP_FILES=true
        - PORT=4040
    ports:
      - '4040:80'
networks:
  default:
    external:
      name: glygen-network-test